
# Generated by Django 4.1 on 2024-04-28 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerDate', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('executionDate', models.DateTimeField()),
                ('place', models.CharField(max_length=200)),
                ('progress', models.IntegerField()),
                ('finishDate', models.DateTimeField(null=True)),
                ('important', models.BooleanField(default=False)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('done', models.BooleanField(default=False)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistic.event')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricDeletedEvents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registerDate', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('executionDate', models.DateField()),
                ('place', models.CharField(max_length=200)),
                ('progress', models.IntegerField()),
                ('finishDate', models.DateTimeField(null=True)),
                ('important', models.BooleanField(default=False)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
