# Generated by Django 4.1 on 2024-04-22 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricDeletedEvents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registerDate', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('executionDate', models.DateField()),
                ('place', models.CharField(max_length=200)),
                ('progress', models.IntegerField()),
                ('finishDate', models.DateTimeField(null=True)),
                ('important', models.BooleanField(default=False)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
