# Generated by Django 4.1 on 2024-05-05 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='feedback',
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='eventName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistic.event'),
        ),
    ]
