name: CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12.3
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.3

    - name: Install dependencies
      run: |
        pip install django
        pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
        pip install -r requirements.txt

    

    - name: Run tests
      run: |        
        python manage.py test logistic.tests.test_checklist
        python manage.py test logistic.tests.test_event
        python manage.py test logistic.tests.test_user
        python manage.py test logistic.tests.test_task
        python manage.py test logistic.test.forms_test
        python manage.py test logistic.test.models_test
        python manage.py test logistic.test.templates_test
        python manage.py test logistic.test.views_test      